### ISSUE TITLE
Real-time apps con Angular y Firebase

### ISSUE THREAD

**Issue by raprav** [AlmeriaJS/talks#1]
# Title / Título
Real-time apps con Angular y Firebase

# Description / Descripción
Las nuevas herramientas para el desarrollo web en cliente han hecho que, con el data-binding, hablar de "manipulación del DOM" nos suene muy a los 00's. 

Presentamos un nuevo concepto en el que nos llevamos el data-binding a la nube, permitiendo explorar nuevas posibilidades en el desarrollo de aplicaciones colaborativas en tiempo real.

Se hará una breve introducción al data-binding de Angular y una presentación de las herramientas que ofrece Firebase, centrándonos en [Firebase Realtime Database](https://firebase.google.com/docs/database/?hl=es).

# Speaker Bio / Bio del Ponente
Rafael Prats Vieira ([@raprav](https://twitter.com/raprav)). Back-end developer, javascripter y procrastinador en [@CodertyStudio](https://twitter.com/codertystudio)

# Level / Nivel
Iniciación. Conceptual.

# Duration / Duración
Una hora

**Comment by alo** [comment]
Todo un lujo de charla!
