### ISSUE TITLE
App con Ionic2 y Firebase + Facebook Auth

### ISSUE THREAD

**Issue by Jhonsensf** [AlmeriaJS/talks#2]
# Título: App con Ionic2 y Firebase + Facebook Auth

# Descripción:
Aprovechando la gran charla de @raprav propongo llevar el uso de Angular2 y Firebase al desarrollo movil con el framework por excelencia para ello, Ionic.

Instalaremos las herramientas necesariar para el entorno de trabajo y crearemos una ssencilla app que se conectará a una BBDD Firebase. Además implementaremos FirebasrAuth para poder loguearnos en la app con Facebook.

# Ponente
@jhonsensf,  Full-stack developer at @Coderty

#€ Nivel:
Iniciación

# Duración:
30 minutos a una hora

**Comment by alo** [comment]
Perfecto! El miércoles 28 en "La Oficina"
[Meetup](https://www.meetup.com/es-ES/almeriajs/events/240942350/)
