### ISSUE TITLE
Kotlin JS, ¿Por qué conformarnos solo con TS, Dart, Coffeescript, JSX...?

### ISSUE THREAD

**Issue by miguelangellv** [AlmeriaJS/talks#3]
# Title / Título
Kotlin JS, ¿Por qué conformarnos solo con TS, Dart, Coffeescript, JSX...?

# Description / Descripción
Kotlin es un lenguaje que inicialmente nació para sustituir a Java ofreciendo total compatibilidad con él a nivel binario, pero desde hace un tiempo también permite compilar nuestro código a Javascript y comunicarnos con las bibliotecas de este. 

A diferencia de TS o Coffeescript, Kotlin no es un superset de Javascript, es un lenguaje totalmente nuevo, fuertemente tipado, con características de los últimos lenguajes y toques funcionales, y gracias a su versión JVM, podremos usar el mismo lenguaje en la cara del servidor (¿Spring Boot por ejemplo?) 

# Speaker Bio / Bio del Ponente

Miguel Ángel López, programador con más de 7 años de experiencia, 5 de ellos en la empresa almeriense Realtrack Systems, en distintas modalidades, destacando programación Android, sistemas empotrados, web y Arduino.

# Level / Nivel
Intermedio

# Duration / Duración
45 minutos

**Comment by raprav** [comment]
Genial @MiguelAngelLV, va a estar muy interesante fijo!

Tenemos reservada La Oficina el miércoles 26 de julio a las 19:00 así que ya es oficial.

Para este fin de semana publicaremos el Meetup, crearemos la actividad en Hacklab y planificaremos algunos tweets.

**Comment by alo** [comment]
Nice!
