### ISSUE TITLE
Angular usando un ESP8266 como servidor 

### ISSUE THREAD

**Issue by miguelangellv** [AlmeriaJS/talks#4]
# Title / Título
Control de un ESP8266 usando Angular 

# Description / Descripción
Los ESP8266 son unas pequeñas placas compatibles con Arduino. Son muy baratas (3-4$), disponen de wifi y 3MB de memoria.

Con un poco de ingenio y gracias a AOT podremos alojar nuestra web Angular en el propio dispositivo y con unas llamadas a una API REST controlar el dispositivo (encender/apagar LEDs, controlar un servo...)

En la charla crearemos una aplicación muy sencilla usando Angular + Material, la instalaremos en nuestro ESP8266 y con unas pocas líneas de Arduino podremos controlar unos LED's RGB así como mover un servo.

# Speaker Bio / Bio del Ponente
Miguel Ángel López es un culo inquieto amante de los dispositivos inútiles y de usar los útiles para cualquier cosa salvo para la que han sido diseñados.

# Level / Nivel
Conocimiento básico de Angular y C++.

# Duration / Duración
Una hora.

**Comment by raprav** [comment]
@MiguelAngelLV confirmamos para el 23 noviembre?

**Comment by miguelangellv** [comment]
Chachi!

**Comment by alo** [comment]
@MiguelAngelLV es el 30! @raprav no contaba con él. Va a ser el primer AlmeriaJS que caiga en el último jueves del mes ...

**Comment by raprav** [comment]
Sorry!

**Comment by alo** [comment]
👌🏽
