### ISSUE TITLE
Opensourcing con Cabeza: De github a npm

### ISSUE THREAD

**Issue by antoniogenaro** [AlmeriaJS/talks#5]
# Title / Título

Opensourcing con Cabeza: De github a npm

# Description / Descripción

Desmitificamos el uso de herramientas de colaboración de proyectos opensource, llevando el típico ejemplo de git clone/pull un pasito más allá.

Partiendo de una introducción para asentar los conceptos básicos de git, se mostrarán las herramientas que ofrece Github y cómo la plataforma en si propicia el desarrollo colaborativo y otorgando visibilidad al contribuyente.

También mostraremos cómo se transforma un puñado de ficheros de código fuente en un paquete de npm; servido, instalable y utilizable públicamente con el gestor de paquetes con la biblioteca más extensa del momento.

# Speaker Bio / Bio del Ponente

Joven promesa del front-end. Amante de lo friki y así lo demuestran sus camisetas. Nunca hace lorem ipsums, siempre tiene algo que decir. Rookie del año en [Coderty](https://twitter.com/codertystudio).

# Level / Nivel

Iniciación

# Duration / Duración

30 minutos a una hora

**Comment by raprav** [comment]
[Meetup](https://www.meetup.com/es-ES/almeriajs/events/244461947/)

Muchas gracias @antoniogenaro
