### ISSUE TITLE
Nueva charla: Introducción a Kubernetes

### ISSUE THREAD

**Issue by Indavelopers** [AlmeriaJS/talks#6]
# Title / Título
Introducción a Kubernetes: infraestructura cloud-native escalable

# Description / Descripción
[Kubernetes](https://kubernetes.io/) es un orquestador de contenedores para crear despliegues de arquitectura definidos por código.

Los contenedores nos permiten desplegar microservicios y aplicaciones sin problemas de dependencias y con una escalabilidad más flexible y ágil que con VMs.
K8s nos permite gestionar los contenedores, recursos y VMs en nuestro despliegue de forma automática, autoescalando y reparando la arquitectura por nosotros, ayudándonos en nuestra labor de devOps.
Además, con K8s todo es código declarativo, por lo que podemos crear flujos de CI/CD automáticos, revertir a un estado de arquitectura anterior y reutilizar la infraestructura como código en desarrollos futuros.
Es uno de los proyectos open-source con más contribuidores de la actualidad, que se ha convertido en el estándar de facto, siendo usado para administrar infraestructuras en un gran número de proyectos por todo el mundo, y continúa creciendo.

Si quieres conocer el futuro de la gestión de infraestructura online y ver cómo K8s y los contenedores están sustituyendo a todo el desarrollo basado en monolitos, ven con nosotros a esta intro + demo práctica con mucha explicación simplificada y nada de jerga de administración de sistemas.

Link a las diapositivas: (http://bit.ly/k8s-almeriajs)[http://bit.ly/k8s-almeriajs]

# Speaker Bio / Bio del Ponente
Marcos Manuel Ortega es consultor, desarrollador y formador en cloud computing, big data e IoT en Indavelopers. También es responsable de HW, IoT y big data en Total Grow Life. Especialista en Google Cloud Platforma con más de 5 años de experiencia en proyectos de iniciativa propia y para terceros. Además le gusta la comunidad y es organizador de GDG Almería, DataBeers Almería y GDG Cloud Español.

# Level / Nivel
Iniciación

# Duration / Duración
35' + Q&A

**Comment by alo** [comment]
YEAH! 🤙🏽
